spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    schema: user_service
    data: classpath:data.sql
    initialization-mode: always
  application:
    name: user_service


  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: 'true'
        format_sql: 'true'
        default_schema: user_service


server:
  port: 7676

