spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    schema: classpath:init.sql
  application:
    name: user_service

  sql:
    init:
      data-locations: classpath:init.sql

  jpa:
    show-sql: true
    hibernate:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: 'true'
        format_sql: 'true'
        default_schema: user_service


server:
  port: 8080

