spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  application:
    name: order-service

  sql:
    init:
      data-locations: classpath:init.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: 'true'
        format_sql: 'true'
        default_schema: order_service

feign:
  book-management-service:
   url: http://localhost:7979
  order-service:
   url: http://localhost:7575
  user-service:
    url: http://localhost:7676



server:
  port: 7575







