spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  application:
    name: book-management-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: 'true'
        format_sql: 'true'
        default_schema: book-management-service
        hbm2ddl.auto: validate


server:
  port: 7979